
services:
  app:
    container_name: app_api
    build:
      context: ./app
      dockerfile: Dockerfile
      #image: paulogomes/app_api:latest  # Add this line
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      #- "8000:8000"
      - "${APP_PORT}:8000"  # Use environment variable for port mapping
    volumes:
      - ./app:/app  # Mount the app directory for development
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    container_name: "postgres" 
    build:
      context: ./postgres
      dockerfile: Dockerfile
      #image: paulogomes/postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network

networks:
  app-network:
    name: "app-network"
    driver: bridge

volumes:
  postgres-data:   # Define the volume for PostgreSQL data
