
services:
  app:
    image: diogoromero/dirtychewbacca:latest
    container_name: dirtychewbacca
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - 8000:8000  # Use environment variable for port mapping
    volumes:
      - ./app:/app  # Mount the app directory for development
    networks:
      - app-network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:14
    container_name: "postgresdb" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network


  flyway:
    image: flyway/flyway
    container_name: "flyway" 
    command: -url=jdbc:postgresql://postgresdb:5433/postgres  -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - app-network
    depends_on:
      - postgresdb

networks:
  app-network:
    name: "app-network"
    driver: bridge

volumes:
  postgres-data:   # Define the volume for PostgreSQL data
